### ISSUE TITLE
Bug in example code in readme

### ISSUE THREAD

**Issue by m1geo** [eta-systems/MAX11615#1]
Hey, in your `README.md` you have the following snippet of example code:

```cpp
    uint8_t adc_value = 0;
    MAX11615_ADC_Read(&adcDriver_1, 0, adc_value); 
```
However, the adc output return value is `uint16_t* val` as here:
https://github.com/eta-systems/MAX11615/blob/316c1fda43527606f7775e90efb2e91d2a0d64de/src/MAX11615.c#L94

Makes sense this would 16b, as the ADC itself is 12bit.

Thanks for the driver. Just a simple readme tweak may help others :)

**Comment by m1geo** [comment]
Also, just noticed that the example code should pass the address of `adc_value` to the ADC_Read function so it should be:
```cpp
    uint16_t adc_value = 0;
    MAX11615_ADC_Read(&adcDriver_1, 0, &adc_value); 
```

Thanks - hope that helps someone.

**Comment by mnemocron** [comment]
Good catch! Thank you :)
